server:
  port: 8090
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  tomcat:
    uri-encoding: UTF-8

spring:
  mvc:
    view:
      prefix:  /WEB-INF/views/
      suffix: .jsp  
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 30MB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/guesssong?serverTimezone=Asia/Seoul
    username: root
    password: root1234
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
        
        